version: '3.8'

services:
  php-apache:
    build: .
    container_name: php-apache
    ports:
      - "8080:80"   # Map port 80 in the container to port 8080 on your host machine
    volumes:
      - ./app:/var/www/html   # Mount your app directory to the container
    depends_on:
      - mysql   # Ensure MySQL starts before PHP
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: shop_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "8081:80"  # Access phpMyAdmin at http://localhost:8081
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network: